name: distributed_NNs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mpi4py
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - pytorch
  - jupyter
  - torchvision
  - pyarrow
  - pytest
