name: shallowspeed
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - mpi4py
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - jupyter
  - pyarrow
  - pytest
  - pytest-mpi
  - pre-commit
